name: Build

on: push

jobs:
  buildConfig:
    name: Get Build Config
    uses: ./.github/workflows/BuildConfig.yml

  build:
    name: Build Job

    needs: buildConfig
    runs-on: self-hosted

    outputs:
      appPoolName: ${{ secrets.DEV_APP_POOL_NAME }}
      targetLocation: ${{ secrets.DEV_TARGET_LOCATION }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/pcholera/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output .\Publish /p:AssemblyVersion=${{ needs.buildConfig.outputs.buildVersion }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TestProject - ${{ needs.buildConfig.outputs.buildVersion }}
        path: .\Publish

    - name: Save Artifact Locally
      run: |
        Copy-Item -Path .\Publish -Destination ..\Publish\TestProject\${{ needs.buildConfig.outputs.buildVersion }} -recurse -Force

  deploy_to_dev:
    name: Deploy To Dev
    needs: [ build, buildConfig ]
    uses: ./.github/workflows/Deploy.yml
    with:
      appPoolName: ${{ needs.build.outputs.appPoolName }}
      targetLocation: ${{ needs.build.outputs.targetLocation }}
      assemblyVersion: ${{ needs.buildConfig.outputs.assemblyVersion }}