name: Build

on: push

jobs:
  buildConfig:
    name: Get Build Config
    uses: ./.github/workflows/BuildConfig.yml

  build:
    name: Build Job

    needs: buildConfig
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/pcholera/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output .\Publish /p:AssemblyVersion=${{ needs.versionNumber.outputs.buildVersion }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TestProject - ${{ needs.versionNumber.outputs.buildVersion }}
        path: .\Publish

    - name: Save Artifact Locally
      run: |
        Copy-Item -Path .\Publish -Destination ..\Publish\TestProject\${{ needs.versionNumber.outputs.buildVersion }} -recurse -Force

    - name: Deploy To Dev
      run: |
          curl -X POST https://api.github.com/repos/pcholera/TestProject/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Deploy To Dev Environment", "client_payload": { "assemblyVersion": "'"${{ needs.versionNumber.outputs.buildVersion }}"'" }}'