name: Deploy To Production Environment

on:
  workflow_dispatch:
    inputs:
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string

env:
  prodAppPool: ${{ secrets.PRODAPPPOOL }}
  prodTargetLocation: ${{ secrets.PRODTARGETLOCATION }}

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/Deploy.yml
    with:
      appPoolName: ${{ env.prodAppPool }}
      targetLocation: ${{ env.prodTargetLocation }}
      assemblyVersion: ${{ github.event.inputs.assemblyVersion }}