name: Deploy To Production Environment

on:
  workflow_dispatch:
    inputs:
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/Deploy.yml
    with:
      assemblyVersion: ${{ github.event.inputs.assemblyVersion }}
      environment: production
    # secrets:
    #   appPoolName: ${{ secrets.PRODAPPPOOL }}
    #   targetLocation: ${{ secrets.PRODTARGETLOCATION }}