name: Deploy

on:
  workflow_call:
    inputs:
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string
      environment:
        description: 'Deployment Environment'
        default: ''
        required: true
        type: string
    # secrets:
    #   appPoolName:
    #     description: 'IIS Application Pool Name'
    #     required: true
    #   targetLocation:
    #     description: 'Trarget Location For Application'
    #     required: true

jobs:      
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Artifacts Location
        id: Artifact
        run: echo "::set-output name=ArtifactLocation::..\Publish\TestProject\${{ inputs.assemblyVersion }}"

      - name: Stop App Pool
        run: .\DeploymentScript\StopAppPool.ps1 ${{ secrets.appPoolName }}

      - name: Publish File To Server
        run: |
          if (test-path "${{ secrets.targetLocation }}")
          {
            Remove-Item -Recurse "${{ secrets.targetLocation }}"
          }
          Copy-Item -Path ${{ steps.Artifact.outputs.ArtifactLocation }} -Destination "${{ secrets.targetLocation }}" -recurse -Force

      - name: Start App Pool
        run: .\DeploymentScript\StartAppPool.ps1 ${{ secrets.appPoolName }}