name: Deploy

on:
  workflow_call:
    inputs:
      appPoolName:
        description: 'IIS Application Pool Name'
        default: 'Espresso'
        required: true
        type: string
      targetLocation:
        description: 'Trarget Location For Application'
        default: '\\nyallegrowebd01\c$\inetpub\wwwroot\Espresso'
        required: true
        type: string
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string

jobs:      
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Artifacts Location
        id: Artifact
        run: echo "::set-output name=ArtifactLocation::..\Publish\TestProject\${{ inputs.assemblyVersion }}"

      - name: Stop App Pool
        run: .\DeploymentScript\StopAppPool.ps1 ${{ inputs.appPoolName }}

      - name: Publish File To Server
        run: |
          if (test-path "${{ inputs.targetLocation }}")
          {
            Remove-Item -Recurse "${{ inputs.targetLocation }}"
          }
          Copy-Item -Path ${{ steps.Artifact.outputs.ArtifactLocation }} -Destination "${{ inputs.targetLocation }}" -recurse -Force

      - name: Start App Pool
        run: .\DeploymentScript\StartAppPool.ps1 ${{ inputs.appPoolName }}