name: Deploy To Dev Environment

on:
  workflow_dispatch:
    inputs:
      assemblyVersion:
        description: 'Assembly Version'
        default: ''
        required: true
        type: string

env:
  devAppPool: ${{ secrets.DEVAPPPOOL }}
  devTargetLocation: ${{ secrets.DEVTARGETLOCATION }}

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/Deploy.yml
    with:
      appPoolName: ${{ env.devAppPool }}
      targetLocation: ${{ env.devTargetLocation }}
      assemblyVersion: ${{ github.event.inputs.assemblyVersion }}